import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export async function computeToolRegistryContent(): Promise<string> {
  const toolsDir = path.resolve(__dirname, "../src/tools");

  const entries = await fs.readdir(toolsDir, { withFileTypes: true });

  const toolFiles = entries
    .filter((entry) => {
      if (!entry.isFile()) return false;
      const name = entry.name;
      if (!name.endsWith(".ts")) return false;
      if (name === "index.ts" || name === "generated-registry.ts" || name === "types.ts") return false;
      if (name.endsWith(".test.ts") || name.endsWith(".spec.ts") || name.endsWith(".d.ts")) return false;
      return true;
    })
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  const imports: string[] = [];
  const entriesCode: string[] = [];

  for (const fileName of toolFiles) {
    const baseName = fileName.slice(0, -3); // remove .ts
    const safeIdentifier = baseName.replace(/[^a-zA-Z0-9_$]/g, "_");
    const regId = `register_${safeIdentifier}`;
    const metaId = `meta_${safeIdentifier}`;
    imports.push(`import ${regId}, { toolMeta as ${metaId} } from "./${baseName}.js";`);
    entriesCode.push(`  {\n    register: ${regId},\n    meta: ${metaId},\n  },`);
  }

  return [
    "// AUTO-GENERATED FILE.",
    "// DO NOT EDIT MANUALLY.",
    "// Generated by scripts/generate-tool-registry.ts",
    "",
    'import type { McpServer } from "@modelcontextprotocol/server";',
    'import type { ServerContext } from "../core/server-context.js";',
    'import type { ToolMetadata } from "./types.js";',
    ...imports,
    "",
    "export type ToolRegistrar = (server: McpServer, context?: ServerContext) => void;",
    "",
    "export interface ToolEntry {",
    "  register: ToolRegistrar;",
    "  meta: ToolMetadata;",
    "}",
    "",
    "export const toolEntries: readonly ToolEntry[] = [",
    ...entriesCode,
    "];",
    "",
  ].join("\n");
}

export async function generateToolRegistry(): Promise<void> {
  const toolsDir = path.resolve(__dirname, "../src/tools");
  const outputFile = path.join(toolsDir, "generated-registry.ts");
  const content = await computeToolRegistryContent();
  await fs.writeFile(outputFile, content, "utf-8");
  process.stdout.write(`[Registry Generator] Successfully registered tools into generated-registry.ts\n`);
}

// Only execute directly when run as CLI
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  generateToolRegistry().catch((error) => {
    process.stderr.write(`[Registry Generator Error] ${error instanceof Error ? error.stack || error.message : String(error)}\n`);
    process.exit(1);
  });
}
