import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface ExtractedBuildMetadata {
  packageName: string;
  packageVersion: string;
  cliBinName: string;
}

/**
 * Pure and testable validator extracting build metadata from package.json without silent fallbacks.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function extractBuildMetadata(packageJson: any): ExtractedBuildMetadata {
  if (!packageJson || typeof packageJson !== "object") {
    throw new Error("package.json content must be a valid JSON object.");
  }

  // 1. Validate package name
  if (typeof packageJson.name !== "string" || packageJson.name.trim().length === 0) {
    throw new Error('package.json "name" field is required and must be a non-empty string.');
  }
  const packageName = packageJson.name.trim();

  // 2. Validate package version
  if (typeof packageJson.version !== "string" || packageJson.version.trim().length === 0) {
    throw new Error('package.json "version" field is required and must be a non-empty string.');
  }
  const packageVersion = packageJson.version.trim();

  // 3. Validate package bin (must be an object with exactly 1 entry for this project)
  if (
    !packageJson.bin ||
    typeof packageJson.bin !== "object" ||
    Array.isArray(packageJson.bin)
  ) {
    throw new Error(
      'package.json "bin" field is required and must be an object defining the CLI executable.'
    );
  }

  const binKeys = Object.keys(packageJson.bin);
  if (binKeys.length === 0) {
    throw new Error('package.json "bin" object must contain at least one binary entry.');
  }

  if (binKeys.length > 1) {
    throw new Error(
      `package.json "bin" object contains multiple entries (${binKeys.join(", ")}). Exactly 1 CLI binary is expected for this project.`
    );
  }

  const cliBinName = binKeys[0].trim();
  if (cliBinName.length === 0) {
    throw new Error('package.json "bin" key name cannot be empty.');
  }

  return {
    packageName,
    packageVersion,
    cliBinName,
  };
}

export async function computeBuildMetaContent(): Promise<string> {
  const rootDir = path.resolve(__dirname, "..");
  const packageJsonPath = path.join(rootDir, "package.json");

  const packageJsonRaw = await fs.readFile(packageJsonPath, "utf-8");
  const packageJson = JSON.parse(packageJsonRaw);

  const { packageName, packageVersion, cliBinName } = extractBuildMetadata(packageJson);

  return [
    "// AUTO-GENERATED FILE.",
    "// DO NOT EDIT MANUALLY.",
    "// Generated by scripts/generate-build-meta.ts",
    "",
    `export const PACKAGE_NAME = ${JSON.stringify(packageName)};`,
    `export const PACKAGE_VERSION = ${JSON.stringify(packageVersion)};`,
    `export const CLI_BIN_NAME = ${JSON.stringify(cliBinName)};`,
    "",
  ].join("\n");
}

export async function generateBuildMeta(): Promise<void> {
  const rootDir = path.resolve(__dirname, "..");
  const packageJsonPath = path.join(rootDir, "package.json");
  const generatedDir = path.join(rootDir, "src", "generated");
  const outputFile = path.join(generatedDir, "build-meta.ts");

  const packageJsonRaw = await fs.readFile(packageJsonPath, "utf-8");
  const packageJson = JSON.parse(packageJsonRaw);

  const { packageName, packageVersion, cliBinName } = extractBuildMetadata(packageJson);

  await fs.mkdir(generatedDir, { recursive: true });
  const content = await computeBuildMetaContent();

  await fs.writeFile(outputFile, content, "utf-8");
  process.stdout.write(
    `[Build Meta Generator] Successfully generated build-meta.ts (${packageName}@${packageVersion}, bin: ${cliBinName})\n`
  );
}

// Only run generation when executed directly as a script
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  generateBuildMeta().catch((error) => {
    process.stderr.write(
      `[Build Meta Generator Error] ${error instanceof Error ? error.stack || error.message : String(error)}\n`
    );
    process.exit(1);
  });
}
