// AUTO-GENERATED FILE.
// DO NOT EDIT MANUALLY.
// Generated by scripts/generate-tool-registry.ts

import type { McpServer } from "@modelcontextprotocol/server";
import type { ServerContext } from "../core/server-context.js";
import type { ToolMetadata } from "./types.js";
import register_cache_stats, { toolMeta as meta_cache_stats } from "./cache-stats.js";
import register_cached_prime_count, { toolMeta as meta_cached_prime_count } from "./cached-prime-count.js";
import register_echo, { toolMeta as meta_echo } from "./echo.js";
import register_fetch_url, { toolMeta as meta_fetch_url } from "./fetch-url.js";
import register_file_info, { toolMeta as meta_file_info } from "./file-info.js";
import register_heavy_compute_main, { toolMeta as meta_heavy_compute_main } from "./heavy-compute-main.js";
import register_heavy_compute_worker, { toolMeta as meta_heavy_compute_worker } from "./heavy-compute-worker.js";
import register_list_directory, { toolMeta as meta_list_directory } from "./list-directory.js";
import register_ping, { toolMeta as meta_ping } from "./ping.js";
import register_read_text_file, { toolMeta as meta_read_text_file } from "./read-text-file.js";
import register_reset_cache, { toolMeta as meta_reset_cache } from "./reset-cache.js";
import register_reset_metrics, { toolMeta as meta_reset_metrics } from "./reset-metrics.js";
import register_search_files, { toolMeta as meta_search_files } from "./search-files.js";
import register_search_text, { toolMeta as meta_search_text } from "./search-text.js";
import register_server_metrics, { toolMeta as meta_server_metrics } from "./server-metrics.js";
import register_system_stats, { toolMeta as meta_system_stats } from "./system-stats.js";
import register_worker_pool_stats, { toolMeta as meta_worker_pool_stats } from "./worker-pool-stats.js";
import register_workspace_roots, { toolMeta as meta_workspace_roots } from "./workspace-roots.js";

export type ToolRegistrar = (server: McpServer, context?: ServerContext) => void;

export interface ToolEntry {
  register: ToolRegistrar;
  meta: ToolMetadata;
}

export const toolEntries: readonly ToolEntry[] = [
  {
    register: register_cache_stats,
    meta: meta_cache_stats,
  },
  {
    register: register_cached_prime_count,
    meta: meta_cached_prime_count,
  },
  {
    register: register_echo,
    meta: meta_echo,
  },
  {
    register: register_fetch_url,
    meta: meta_fetch_url,
  },
  {
    register: register_file_info,
    meta: meta_file_info,
  },
  {
    register: register_heavy_compute_main,
    meta: meta_heavy_compute_main,
  },
  {
    register: register_heavy_compute_worker,
    meta: meta_heavy_compute_worker,
  },
  {
    register: register_list_directory,
    meta: meta_list_directory,
  },
  {
    register: register_ping,
    meta: meta_ping,
  },
  {
    register: register_read_text_file,
    meta: meta_read_text_file,
  },
  {
    register: register_reset_cache,
    meta: meta_reset_cache,
  },
  {
    register: register_reset_metrics,
    meta: meta_reset_metrics,
  },
  {
    register: register_search_files,
    meta: meta_search_files,
  },
  {
    register: register_search_text,
    meta: meta_search_text,
  },
  {
    register: register_server_metrics,
    meta: meta_server_metrics,
  },
  {
    register: register_system_stats,
    meta: meta_system_stats,
  },
  {
    register: register_worker_pool_stats,
    meta: meta_worker_pool_stats,
  },
  {
    register: register_workspace_roots,
    meta: meta_workspace_roots,
  },
];
